accelerator_kwargs/step_scheduler_with_optimizer: false
adap_kl_ctrl: true
backward_batch_size: 60
batch_size: 60
cliprange: 0.2
cliprange_value: 0.2
compare_steps: 1
early_stopping: false
exp_name: train
forward_batch_size: null
gamma: 1
global_backward_batch_size: 180
global_batch_size: 180
gradient_accumulation_steps: 10
gradient_checkpointing: false
horizon: 10000
init_kl_coef: 0.2
is_encoder_decoder: false
is_peft_model: true
kl_penalty: kl
lam: 0.95
learning_rate: 1e-7
log_with: tensorboard
max_grad_norm: 1.0
mini_batch_size: 6
model_name: /root/autodl-tmp/models/Qwen2.5-Math-1.5B-Instruct
optimize_cuda_cache: null
optimize_device_cache: true
ppo_epochs: 2
project_kwargs/logging_dir: /root/autodl-tmp/LIRM_unit/Version_3/saves/Qwen1.5-7B/limr_ppo_run6/runs/Mar30_18-46-10_autodl-container-5e9a44960d-c45d7e6a
query_dataset: imdb
ratio_threshold: 10.0
remove_unused_columns: false
reward_model: sentiment-analysis:lvwerra/distilbert-imdb
score_clip: null
seed: 42
steps: 20000
target: 0.1
target_kl: 1
task_name: null
total_ppo_epochs: 334
tracker_project_name: trl
use_score_norm: true
use_score_scaling: true
vf_coef: 0.1
whiten_rewards: true
world_size: 3
